### ISSUE TITLE
Restricted APIs

### ISSUE THREAD

**Issue by xallavon** [DECENTfoundation/DECENT-Network#199] opened 2017-07-05 16:17 UTC
Hi. Is there any way to access restricted APIs without using websocket? 
I.e. when using curl, I get the following output.

```
xallavon:~$ curl --data '{"id":1, "method":"call", "params":[1,"login",["bytemaster", "supersecret"]]}' http://127.0.0.1:8090/rpc
{"id":1,"result":true}
xallavon:~$ curl --data '{"id":1, "method"history",[]]}' http://127.0.0.1:8090p://127.0.0.1:8090/rpc
{"id":1,"error":{"code":1,"message":"10 assert_exception: Assert Exception\n_history_api: \n    {}\n    th_a  api.cpp:251 history","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"api.cpp","line":251,"method":"history","hostname":"","thread_name":"th_a","timestamp":"2017-07-05T16:14:01"},"format":"_history_api: ","data":{}}]}}}
```

**Comment by tigrangh** [comment] 2017-07-06 09:39
what is your intention?
with netcat or wscat you can have persistent tcp connection and run command one after another, while in this case with curl you're interrupting the session

**Comment by xallavon** [comment] 2017-07-06 12:57
my intention was to use my existing adapter for graphene blockchains with as little tweaks as possible. And it works ok except the fact that connection is dropped after each request, and with your 'login logic' it became useless. 
I tried to make some requests within the same session without breaking tcp connection, but it didn't work. (seems that it's the daemon who closed the connection).
Anyway, version with websocket adapter is already implemented, so I don't really care right now abut this problem. You can close this task if you're not going to make changes in your api.

**Comment by tigrangh** [comment] 2017-07-06 13:41
decent daemon ("decentd") is not communicating with http protocol. curl sends http requests, expects http responses, probably for some reason of miscommunication curl is closing the connection, not decentd.
an alternative you might consider is to use cli_wallet, which will keep persistent tcp connection with decentd and will listen for http requests from curl. cli_wallet supports http protocol by design.

**Closed by tigrangh** 2017-07-06 13:41 UTC
